{
 "title": "Windows - Fabric - Hyper-V (all Nodes) - TV",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "hvgroup", "label": "Hyper-V Group", "query": "HG-FA-Node-Compute" }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Zabbix Compute Alerts (High)",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "HG-FA-Node-Compute" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "severities": [
       3,
       4,
       5
      ],
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default"
     },
     "proxy": { "filter": "" },
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Zabbix Compute Alerts (Warning)",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "HG-FA-Node-Compute" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "severities": [
       2
      ],
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default"
     },
     "proxy": { "filter": "" },
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uptime (in Days)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "dtdhms", "label": "Days" }
   ],
   "targets": [
    {
     "application": { "filter": "General" },
     "functions": [
      {
       "def": {
        "category": "Transform",
        "defaultParams": [
         100
        ],
        "name": "scale",
        "params": [
         {
          "name": "factor",
          "options": [
           100,
           0.01,
           10,
           -1
          ],
          "type": "float"
         }
        ]
       },
       "params": [ "1.157407407407407e-5" ],
       "text": "scale(1.157407407407407e-5)"
      }
     ],
     "group": { "filter": "$hvgroup" },
     "host": { "filter": "/FPPW.*/" },
     "item": { "filter": "System uptime" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VMs in a critical state",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Hyper-V Host" },
     "group": { "filter": "$hvgroup" },
     "host": { "filter": "/FPPW.*/" },
     "item": { "filter": "Hyper-V VMs Critical" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Patchlevel",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "General" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [ "asc" ],
        "name": "sortSeries",
        "params": [
         {
          "name": "direction",
          "options": [
           "asc",
           "desc"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "asc" ],
       "text": "sortSeries(asc)"
      },
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "10000000",
        "avg"
       ],
       "text": "top(10000000, avg)"
      }
     ],
     "group": { "filter": "$hvgroup" },
     "host": { "filter": "/FPPW/" },
     "item": {
      "filter": "Operating System Patchlevel (only UBR)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Logical CPU load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Hyper-V Host" },
     "group": { "filter": "$hvgroup" },
     "host": { "filter": "/FPPW.*/" },
     "item": {
      "filter": "Hyper-V Logical CPU Total Runtime %"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "P2V Ratio (pCores:vCores)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Hyper-V Host" },
     "group": { "filter": "$hvgroup" },
     "host": { "filter": "/FPPW.*/" },
     "item": { "filter": "P2V Ratio (pCores:vCores)" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Number of Handles (total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Hyper-V Host" },
     "group": { "filter": "$hvgroup" },
     "host": { "filter": "/FPPW.*/" },
     "item": { "filter": "Number of Handles (total)" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU Context Switches per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Hyper-V Host" },
     "group": { "filter": "$hvgroup" },
     "host": { "filter": "/FPPW.*/" },
     "item": {
      "filter": "Hyper-V Logical CPU Context Switches per Second"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Wait Time per Dispatch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "application": { "filter": "Hyper-V Host" },
     "group": { "filter": "$hvgroup" },
     "host": { "filter": "/FPPW.*/" },
     "item": {
      "filter": "Hyper-V Virtual CPU Wait Time per Dispatch (avg)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Number of Threads (total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Hyper-V Host" },
     "group": { "filter": "$hvgroup" },
     "host": { "filter": "/FPPW.*/" },
     "item": { "filter": "Number of Threads (total)" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CSV Traffic (Read & Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Hyper-V CSV" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "20",
        "avg"
       ],
       "text": "top(20, avg)"
      }
     ],
     "group": { "filter": "$hvgroup" },
     "host": { "filter": "/FPPW.*/" },
     "item": { "filter": "/CSV IO Write Bytes/s \\b.*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Hyper-V CSV" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "20",
        "avg"
       ],
       "text": "top(20, avg)"
      }
     ],
     "group": { "filter": "$hvgroup" },
     "host": { "filter": "/FPPW.*/" },
     "item": { "filter": "/CSV IO Write Bytes/s \\b.*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CSV redirected Bytes (0 = Good)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Hyper-V CSV" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "20",
        "avg"
       ],
       "text": "top(20, avg)"
      }
     ],
     "group": { "filter": "$hvgroup" },
     "host": { "filter": "/FPPW.*/" },
     "item": {
      "filter": "/CSV Redirected Read Bytes/s \\b.*/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Hyper-V CSV" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "20",
        "avg"
       ],
       "text": "top(20, avg)"
      }
     ],
     "group": { "filter": "$hvgroup" },
     "host": { "filter": "/FPPW.*/" },
     "item": {
      "filter": "/CSV Redirected Write Bytes/s \\b.*/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CSV Latency (Read & Write)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "Hyper-V CSV" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "20",
        "avg"
       ],
       "text": "top(20, avg)"
      }
     ],
     "group": { "filter": "$hvgroup" },
     "host": { "filter": "/FPPW:*/" },
     "item": { "filter": "/CSV IO Read latency \\b.*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Hyper-V CSV" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "20",
        "avg"
       ],
       "text": "top(20, avg)"
      }
     ],
     "group": { "filter": "$hvgroup" },
     "host": { "filter": "/FPPW:*/" },
     "item": { "filter": "/CSV IO Write latency \\b.*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Number of HBA Paths",
   "type": "graph",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Hyper-V CSV" },
     "group": { "filter": "$hvgroup" },
     "host": { "filter": "/FPPW.*/" },
     "item": { "filter": "/Number of HBA Paths:*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "RDMA Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "20",
        "avg"
       ],
       "text": "top(20, avg)"
      }
     ],
     "group": { "filter": "$hvgroup" },
     "host": { "filter": "/FPPW:*/" },
     "item": {
      "filter": "/Incoming RDMA network traffic on.*/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "20",
        "avg"
       ],
       "text": "top(20, avg)"
      }
     ],
     "group": { "filter": "$hvgroup" },
     "host": { "filter": "/FPPW:*/" },
     "item": {
      "filter": "/Outgoing RDMA network traffic on.*/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Traffic of physical NICs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "20",
        "avg"
       ],
       "text": "top(20, avg)"
      }
     ],
     "group": { "filter": "$hvgroup" },
     "host": { "filter": "/FPPW:*/" },
     "item": {
      "filter": "/Incoming network traffic on.*/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network Interfaces" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "20",
        "avg"
       ],
       "text": "top(20, avg)"
      }
     ],
     "group": { "filter": "$hvgroup" },
     "host": { "filter": "/FPPW:*/" },
     "item": {
      "filter": "/Outgoing network traffic on.*/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}